name: "Label PR by file types"
inputs:
  owner:
    required: true
    description: "Repo owner"
  repo:
    required: true
    description: "Repo name"
  pr_number:
    required: true
    description: "PR number"
  token:
    required: true
    description: "GitHub token"
runs:
  using: composite
  steps:
    - uses: tau-github-actions-for-testing/tau-own-action-pull-request@main
      with:
        owner:   ${{ inputs.owner }}
        repo:    ${{ inputs.repo }}
        pr_number: ${{ inputs.pr_number }}
        token:   ${{ inputs.token }}

