name: 'PR Labeler (Java)'
description: 'Labels pull requests based on changed file types'
inputs:
  owner:
    description: 'Repository owner e.g. ${{ github.repository_owner }}'
    required: true
  repo:
    description: 'Repository name e.g. ${{ github.event.repository.name }}'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  token:
    description: 'GitHub token (${{ secrets.GITHUB_TOKEN }})'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
